name: Python Code Quality Check

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Pylint Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      max-parallel: 3  # CORRECCIÓN: Fuera del bloque matrix
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        [ -f requirements.txt ] && pip install -r requirements.txt
        
    - name: Run Pylint analysis
      run: |
        pylint --output-format=colorized \
               --disable=C0114,C0115,C0116 \
               $(git ls-files '*.py' | grep -v 'tests/')
        
    - name: Upload results as artifact (optional)
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: pylint-results-${{ matrix.python-version }}
        path: pylint_output.log
